/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import loginPage.Main;

/**
 *
 * @author Justin PC
 */
public class accountDetails extends javax.swing.JFrame {

    /**
     * Creates new form accountDetails
     */
    public accountDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        U_ID = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        UserGroup = new javax.swing.JPanel();
        AdminIcon = new javax.swing.JPanel();
        AdminIconImg = new javax.swing.JLabel();
        user_Name = new javax.swing.JLabel();
        ChangePassGroup = new javax.swing.JPanel();
        AdminIcon1 = new javax.swing.JPanel();
        AdminIconImg1 = new javax.swing.JLabel();
        user_Name1 = new javax.swing.JLabel();
        fname = new textfield.TextField();
        lname = new textfield.TextField();
        txtDate = new textfield.TextField();
        mobileNum = new textfield.TextField();
        emailPane = new textfield.TextField();
        cancelButton = new textfield.MyButton();
        submitButton = new textfield.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N
        jLabel3.setText("Helios");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("Current User ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        U_ID.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        U_ID.setText("ID Place Holder");
        jPanel2.add(U_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 130));

        navBar.setBackground(new java.awt.Color(0, 0, 0));
        navBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserGroup.setBackground(new java.awt.Color(0, 0, 0));
        UserGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserGroupMouseClicked(evt);
            }
        });
        UserGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIcon.setBackground(new java.awt.Color(0, 0, 0));
        AdminIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIconImg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminIconImg.setForeground(new java.awt.Color(255, 255, 255));
        AdminIconImg.setText("Image");
        AdminIcon.add(AdminIconImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 70));

        UserGroup.add(AdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 110));

        user_Name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_Name.setForeground(new java.awt.Color(255, 255, 255));
        user_Name.setText("USER");
        user_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_NameMouseClicked(evt);
            }
        });
        UserGroup.add(user_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        navBar.add(UserGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 160));

        ChangePassGroup.setBackground(new java.awt.Color(0, 0, 0));
        ChangePassGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePassGroupMouseClicked(evt);
            }
        });
        ChangePassGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIcon1.setBackground(new java.awt.Color(0, 0, 0));
        AdminIcon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIconImg1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminIconImg1.setForeground(new java.awt.Color(255, 255, 255));
        AdminIconImg1.setText("Image");
        AdminIcon1.add(AdminIconImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 70));

        ChangePassGroup.add(AdminIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 110));

        user_Name1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_Name1.setForeground(new java.awt.Color(255, 255, 255));
        user_Name1.setText("Change Password");
        user_Name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_Name1MouseClicked(evt);
            }
        });
        ChangePassGroup.add(user_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        navBar.add(ChangePassGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 160));

        panel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 200, 600));

        fname.setLabelText("First Name");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        panel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 300, -1));

        lname.setLabelText("Last Name");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        panel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 300, -1));

        txtDate.setLabelText("MM--DD--YYYY");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        panel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 300, -1));

        mobileNum.setLabelText("+63");
        mobileNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumActionPerformed(evt);
            }
        });
        panel1.add(mobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 300, -1));

        emailPane.setLabelText("Email");
        emailPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPaneActionPerformed(evt);
            }
        });
        panel1.add(emailPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 297, -1));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        cancelButton.setRadius(50);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 190, 50));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        submitButton.setRadius(50);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        panel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 190, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited

    }//GEN-LAST:event_jLabel3MouseExited

    private void user_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_NameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user_NameMouseClicked

    private void UserGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserGroupMouseClicked

    }//GEN-LAST:event_UserGroupMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // Set the current user details when the window is activated
        Session sess = Session.getInstance();
        if (sess.getUid() == 0) {
            JOptionPane.showMessageDialog(null, "No Account, Log in First!");
            Main lgp = new Main();
            lgp.setVisible(true);
            this.dispose();
        } else {
            user_Name.setText(sess.getFname());
            U_ID.setText(String.valueOf(sess.getUid()));
            fname.setText(sess.getFname());
            lname.setText(sess.getLname());
            txtDate.setText(sess.getBdate());
            mobileNum.setText(sess.getPhone());
            emailPane.setText(sess.getEmail());
        }
    }//GEN-LAST:event_formWindowActivated

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void mobileNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumActionPerformed

    private void emailPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPaneActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         dbConnector dbc = new dbConnector();

        try {
            // Use a prepared statement to avoid SQL injection
            String query = "UPDATE tbl_user SET "
                    + "user_Fname = ?, "
                    + "user_Lname = ?, "
                    + "user_Birthdate = ?, "
                    + "user_Email = ?, "
                    + "user_Phone = ? "
                    + "WHERE user_id = ?"; // Add a WHERE clause to specify which user to update

            // Prepare the statement
            try (PreparedStatement pst = dbc.getConnection().prepareStatement(query)) {
                // Set the parameters for the prepared statement
                pst.setString(1, fname.getText()); // user_Fname
                pst.setString(2, lname.getText()); // user_Lname
                pst.setString(3, txtDate.getText()); // user_Birthdate
                pst.setString(4, emailPane.getText()); // user_Email
                pst.setString(5, mobileNum.getText()); // user_Phone
                pst.setInt(6, Integer.parseInt(U_ID.getText())); // user_id

                // Execute the update
                int rowsUpdated = pst.executeUpdate();

                // Check if the update was successful
                if (rowsUpdated > 0) {
                    dashBoard ds = new dashBoard();
                    JOptionPane.showMessageDialog(this, "User details updated successfully!");
                    this.dispose();
                    ds.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No user found with the specified ID.");
                }
            }
        } catch (SQLException ex) {
            // Handle any SQL errors
            JOptionPane.showMessageDialog(this, "Error updating user details: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void user_Name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_Name1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user_Name1MouseClicked

    private void ChangePassGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePassGroupMouseClicked
        // TODO add your handling code here:
        changePass chp = new changePass();
        chp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangePassGroupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminIcon;
    private javax.swing.JPanel AdminIcon1;
    private javax.swing.JLabel AdminIconImg;
    private javax.swing.JLabel AdminIconImg1;
    private javax.swing.JPanel ChangePassGroup;
    private javax.swing.JLabel U_ID;
    private javax.swing.JPanel UserGroup;
    private textfield.MyButton cancelButton;
    public textfield.TextField emailPane;
    public textfield.TextField fname;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    public textfield.TextField lname;
    public textfield.TextField mobileNum;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel panel1;
    private textfield.MyButton submitButton;
    public textfield.TextField txtDate;
    private javax.swing.JLabel user_Name;
    private javax.swing.JLabel user_Name1;
    // End of variables declaration//GEN-END:variables
}
