/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import loginPage.Main;

/**
 *
 * @author Justin PC
 */
public class changePass extends javax.swing.JFrame {

    /**
     * Creates new form changePass
     */
    public changePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        U_ID = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        UserGroup = new javax.swing.JPanel();
        AdminIcon = new javax.swing.JPanel();
        AdminIconImg = new javax.swing.JLabel();
        user_Name = new javax.swing.JLabel();
        cancelButton = new textfield.MyButton();
        submitButton = new textfield.MyButton();
        oldPass = new textfield.PasswordField();
        confirmPass = new textfield.PasswordField();
        newPass = new textfield.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N
        jLabel3.setText("Helios");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("Current User ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        U_ID.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        U_ID.setText("ID Place Holder");
        jPanel2.add(U_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 130));

        navBar.setBackground(new java.awt.Color(0, 0, 0));
        navBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserGroup.setBackground(new java.awt.Color(0, 0, 0));
        UserGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserGroupMouseClicked(evt);
            }
        });
        UserGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIcon.setBackground(new java.awt.Color(0, 0, 0));
        AdminIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIconImg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminIconImg.setForeground(new java.awt.Color(255, 255, 255));
        AdminIconImg.setText("Image");
        AdminIcon.add(AdminIconImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 70));

        UserGroup.add(AdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 110));

        user_Name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_Name.setForeground(new java.awt.Color(255, 255, 255));
        user_Name.setText("USER");
        user_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_NameMouseClicked(evt);
            }
        });
        UserGroup.add(user_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        navBar.add(UserGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 160));

        panel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 100, 200, 600));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        cancelButton.setRadius(50);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 190, 50));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        submitButton.setRadius(50);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        panel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 190, 50));

        oldPass.setLabelText("Old Password");
        oldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassActionPerformed(evt);
            }
        });
        panel1.add(oldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 297, -1));

        confirmPass.setLabelText("Confirm Password");
        confirmPass.setShowAndHide(true);
        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassActionPerformed(evt);
            }
        });
        panel1.add(confirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 297, -1));

        newPass.setLabelText("Password");
        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        panel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 297, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited

    }//GEN-LAST:event_jLabel3MouseExited

    private void user_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_NameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user_NameMouseClicked

    private void UserGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserGroupMouseClicked

    }//GEN-LAST:event_UserGroupMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            dbConnector dbc = new dbConnector();
            Session sess = Session.getInstance();

            // Fetch the current password from the database
            String query = "SELECT user_Pass FROM tbl_user WHERE user_id = ?";
            try (PreparedStatement pst = dbc.getConnection().prepareStatement(query)) {
                pst.setInt(1, sess.getUid());
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String oldPassHash = rs.getString("user_Pass");
                    String oldPassInputHash = passwordHasher.hashPassword(oldPass.getText());

                    // Verify the old password
                    if (oldPassHash.equals(oldPassInputHash)) {
                        // Check if the new password and confirm password match
                        if (newPass.getText().equals(confirmPass.getText())) {
                            // Hash the new password
                            String newPassHash = passwordHasher.hashPassword(newPass.getText());

                            // Update the password in the database
                            String updateQuery = "UPDATE tbl_user SET user_Pass = ? WHERE user_id = ?";
                            try (PreparedStatement updatePst = dbc.getConnection().prepareStatement(updateQuery)) {
                                updatePst.setString(1, newPassHash);
                                updatePst.setInt(2, sess.getUid());
                                int rowsUpdated = updatePst.executeUpdate();

                                if (rowsUpdated > 0) {
                                    JOptionPane.showMessageDialog(null, "Password updated successfully!");
                                    Main lgn = new Main();
                                    lgn.setVisible(true);
                                    this.dispose();
                                } else {
                                    JOptionPane.showMessageDialog(null, "Failed to update password!");
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "New password and confirm password do not match!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Old password is incorrect!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "User not found!");
                }
            }
        } catch (SQLException | NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassActionPerformed

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        U_ID.setText(""+sess.getUid());
        if(sess.getUid() == 0){
            JOptionPane.showMessageDialog(null, "No Account, Log in First!");
            Main lgp = new Main();
            lgp.setVisible(true);
            this.dispose();
        }
        else{
            
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminIcon;
    private javax.swing.JLabel AdminIconImg;
    private javax.swing.JLabel U_ID;
    private javax.swing.JPanel UserGroup;
    private textfield.MyButton cancelButton;
    private textfield.PasswordField confirmPass;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel navBar;
    public textfield.PasswordField newPass;
    public textfield.PasswordField oldPass;
    private javax.swing.JPanel panel1;
    private textfield.MyButton submitButton;
    private javax.swing.JLabel user_Name;
    // End of variables declaration//GEN-END:variables
}
