/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import config.Session;
import java.awt.Color;
import javax.swing.JOptionPane;
import loginPage.Main;

/**
 *
 * @author user
 */
public class dashBoard extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public dashBoard() {
        initComponents();
    }
    
    Color light = new Color(153,153,153);
    Color dark = new Color(27,27,27); 
    Color bodyColor = new Color(51,204,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        U_ID = new javax.swing.JLabel();
        UserGroup = new javax.swing.JPanel();
        AdminIcon = new javax.swing.JPanel();
        AdminIconImg = new javax.swing.JLabel();
        user_Name = new javax.swing.JLabel();
        AccountDetails = new javax.swing.JPanel();
        AdminIcon1 = new javax.swing.JPanel();
        AdminIconImg1 = new javax.swing.JLabel();
        user_Name1 = new javax.swing.JLabel();

        jLabel2.setBackground(new java.awt.Color(27, 27, 27));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER PAGE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N
        jLabel3.setText("Helios");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(970, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        navBar.setBackground(new java.awt.Color(0, 0, 0));
        navBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        navBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("Current User ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        U_ID.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        U_ID.setText("ID Place Holder");
        jPanel2.add(U_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        navBar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 120, 60));

        UserGroup.setBackground(new java.awt.Color(0, 0, 0));
        UserGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserGroupMouseClicked(evt);
            }
        });
        UserGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIcon.setBackground(new java.awt.Color(0, 0, 0));
        AdminIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIconImg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminIconImg.setForeground(new java.awt.Color(255, 255, 255));
        AdminIconImg.setText("Image");
        AdminIcon.add(AdminIconImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        UserGroup.add(AdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 110));

        user_Name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_Name.setForeground(new java.awt.Color(255, 255, 255));
        user_Name.setText("USER");
        user_Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_NameMouseClicked(evt);
            }
        });
        UserGroup.add(user_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        navBar.add(UserGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 160));

        AccountDetails.setBackground(new java.awt.Color(0, 0, 0));
        AccountDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountDetailsMouseClicked(evt);
            }
        });
        AccountDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIcon1.setBackground(new java.awt.Color(0, 0, 0));
        AdminIcon1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminIconImg1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AdminIconImg1.setForeground(new java.awt.Color(255, 255, 255));
        AdminIconImg1.setText("Image");
        AdminIcon1.add(AdminIconImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 70));

        AccountDetails.add(AdminIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 110));

        user_Name1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        user_Name1.setForeground(new java.awt.Color(255, 255, 255));
        user_Name1.setText("ACCOUNT");
        user_Name1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_Name1MouseClicked(evt);
            }
        });
        AccountDetails.add(user_Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        navBar.add(AccountDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 160));

        panel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 90, 200, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        
    }//GEN-LAST:event_jLabel3MouseExited

    private void user_NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_NameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user_NameMouseClicked

    private void UserGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserGroupMouseClicked

    }//GEN-LAST:event_UserGroupMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        if(sess.getUid() == 0){
            JOptionPane.showMessageDialog(null, "No Account, Log in First!");
            Main lgp = new Main();
            lgp.setVisible(true);
            this.dispose();
        }
        else{
            user_Name.setText(""+sess.getFname());
            U_ID.setText(""+sess.getUid());
        }
    }//GEN-LAST:event_formWindowActivated

    private void user_Name1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_Name1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_user_Name1MouseClicked

    private void AccountDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountDetailsMouseClicked
        // TODO add your handling code here:
        accountDetails acd = new accountDetails();
        acd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccountDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountDetails;
    private javax.swing.JPanel AdminIcon;
    private javax.swing.JPanel AdminIcon1;
    private javax.swing.JLabel AdminIconImg;
    private javax.swing.JLabel AdminIconImg1;
    private javax.swing.JLabel U_ID;
    private javax.swing.JPanel UserGroup;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel user_Name;
    private javax.swing.JLabel user_Name1;
    // End of variables declaration//GEN-END:variables
}
