/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registerPage;

import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import loginPage.Main;

/**
 *
 * @author Justin PC
 */
public class completeUserPage extends javax.swing.JFrame {
    
    private String email; // Field to store the email
    private String password; // Field to store the password
    
    public completeUserPage() {
        this("", ""); // Initialize with an empty email
    }

    /**
     * Creates new form completeUserPage
     */
    public completeUserPage(String email, String password) {
        this.email = email;
        this.password = password;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        setUpPane = new javax.swing.JPanel();
        accInfoPane = new javax.swing.JPanel();
        mobileNum = new textfield.TextField();
        mobileNumLabel = new javax.swing.JLabel();
        descLabel1 = new javax.swing.JLabel();
        typeBox = new javax.swing.JPanel();
        typelbl = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        personInfoPane = new javax.swing.JPanel();
        txtDate = new textfield.TextField();
        dateLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        lname = new textfield.TextField();
        typeBox1 = new javax.swing.JPanel();
        typelbl1 = new javax.swing.JLabel();
        userType = new javax.swing.JComboBox<>();
        submitButton = new textfield.MyButton();
        fname = new textfield.TextField();
        cancelButton = new textfield.MyButton();
        headerPane = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setUpPane.setBackground(new java.awt.Color(255, 255, 255));
        setUpPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accInfoPane.setBackground(new java.awt.Color(255, 255, 255));
        accInfoPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobileNum.setLabelText("+63");
        mobileNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumActionPerformed(evt);
            }
        });
        accInfoPane.add(mobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, -1));

        mobileNumLabel.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        mobileNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        mobileNumLabel.setText("Mobile Number");
        accInfoPane.add(mobileNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 20));

        descLabel1.setBackground(new java.awt.Color(25, 25, 25));
        descLabel1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        descLabel1.setForeground(new java.awt.Color(25, 25, 25));
        descLabel1.setText("Account Information");
        accInfoPane.add(descLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 170, 40));

        typeBox.setBackground(new java.awt.Color(25, 25, 25));
        typeBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typelbl.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        typelbl.setForeground(new java.awt.Color(255, 255, 255));
        typelbl.setText("Type:");
        typeBox.add(typelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        typeComboBox.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type:", "User", "Admin" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });
        typeBox.add(typeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 320, 40));

        accInfoPane.add(typeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 330, 90));

        setUpPane.add(accInfoPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 380, 170));

        personInfoPane.setBackground(new java.awt.Color(255, 255, 255));
        personInfoPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDate.setLabelText("MM--DD--YYYY");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        personInfoPane.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, -1));

        dateLabel.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("Date");
        personInfoPane.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 20));

        descLabel.setBackground(new java.awt.Color(25, 25, 25));
        descLabel.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        descLabel.setForeground(new java.awt.Color(25, 25, 25));
        descLabel.setText("Personal Information");
        personInfoPane.add(descLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 40));

        lname.setLabelText("Last Name");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        personInfoPane.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 300, -1));

        typeBox1.setBackground(new java.awt.Color(255, 255, 255));
        typeBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typelbl1.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        typelbl1.setText("Type:");
        typeBox1.add(typelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        userType.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type:", "User", "Admin" }));
        userType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeActionPerformed(evt);
            }
        });
        typeBox1.add(userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 320, 40));

        personInfoPane.add(typeBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 330, 90));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        submitButton.setRadius(50);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        personInfoPane.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 160, 50));

        fname.setLabelText("First Name");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        personInfoPane.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, -1));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        cancelButton.setRadius(50);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        personInfoPane.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 160, 50));

        setUpPane.add(personInfoPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 900, 330));

        headerPane.setBackground(new java.awt.Color(0, 0, 0));
        headerPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerLabel.setBackground(new java.awt.Color(255, 255, 255));
        headerLabel.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 255, 255));
        headerLabel.setText("Complete your profile ");
        headerPane.add(headerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N
        headerPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 60));

        setUpPane.add(headerPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 90));

        jPanel1.add(setUpPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1040, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mobileNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void userTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTypeActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Validate fields before proceeding
        if (fname.getText().isEmpty() || lname.getText().isEmpty() || txtDate.getText().isEmpty() ||
            mobileNum.getText().isEmpty() || userType.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate mobile number format
        if (!mobileNum.getText().startsWith("+63") || mobileNum.getText().length() != 13) {
            JOptionPane.showMessageDialog(this, "Mobile number must start with +63 and be 13 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate date format (MM-DD-YYYY)
        if (!txtDate.getText().matches("\\d{2}-\\d{2}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Date must be in the format MM-DD-YYYY.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate user type selection
        if (userType.getSelectedItem().equals("Select Type:")) {
            JOptionPane.showMessageDialog(this, "Please select a valid user type.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        dbConnector dbc = new dbConnector();
        try {
            String pass = passwordHasher.hashPassword(this.password);
            // Use a prepared statement to avoid SQL injection
            String query = "INSERT INTO tbl_user (user_Fname, user_Lname, user_Birthdate, user_Email, user_Pass, user_Type, user_Phone, user_Status, u_image) "
                         + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (Connection conn = dbc.getConnection();
                 PreparedStatement pst = conn.prepareStatement(query)) {

                // Set values for the prepared statement
                pst.setString(1, fname.getText());               // user_Fname
                pst.setString(2, lname.getText());               // user_Lname
                pst.setString(3, txtDate.getText());             // user_Birthdate
                pst.setString(4, this.email);                    // user_Email
                pst.setString(5, pass);                         // user_Pass
                pst.setString(6, (String) userType.getSelectedItem()); // user_Type
                pst.setString(7, mobileNum.getText());           // user_Phone
                pst.setString(8, "PENDING");                     // user_Status
                pst.setString(9, "default.png");                     // user_Status

                // Execute the query
                int rowsInserted = pst.executeUpdate();

                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    Main loginMain = new Main();
                    loginMain.setVisible(true);
                    this.dispose(); // Close the current window
                } else {
                    JOptionPane.showMessageDialog(this, "Registration failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(completeUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        CreatePass nw = new CreatePass();
        nw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(completeUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(completeUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(completeUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(completeUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new completeUserPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accInfoPane;
    private textfield.MyButton cancelButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel descLabel1;
    private textfield.TextField fname;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private textfield.TextField lname;
    private textfield.TextField mobileNum;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JPanel personInfoPane;
    private javax.swing.JPanel setUpPane;
    private textfield.MyButton submitButton;
    private textfield.TextField txtDate;
    private javax.swing.JPanel typeBox;
    private javax.swing.JPanel typeBox1;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typelbl;
    private javax.swing.JLabel typelbl1;
    private javax.swing.JComboBox<String> userType;
    // End of variables declaration//GEN-END:variables
}
