package registerPage;

import java.awt.Color;
import javax.swing.JOptionPane;
import loginPage.Main;

public class CreatePass extends javax.swing.JFrame {
    
    private String email; // Field to store the email
    
    public CreatePass() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
       
    }

    /**
     * Creates new form Test
     */
    public CreatePass(String email) {
        this.email = email;
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
    }
    
    // Method to validate password
    private boolean isValidPassword(String password) {
        // Minimum length of 8 characters
        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Check for at least one uppercase letter
        if (!password.matches(".*[A-Z].*")) {
            JOptionPane.showMessageDialog(this, "Password must contain at least one uppercase letter.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Check for at least one lowercase letter
        if (!password.matches(".*[a-z].*")) {
            JOptionPane.showMessageDialog(this, "Password must contain at least one lowercase letter.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Check for at least one digit
        if (!password.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "Password must contain at least one number.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Check for at least one special character
        if (!password.matches(".*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?].*")) {
            JOptionPane.showMessageDialog(this, "Password must contain at least one special character.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        passField = new textfield.PasswordField();
        confirmField = new textfield.PasswordField();
        descLabel = new javax.swing.JLabel();
        descLabel1 = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        signUpButton = new textfield.MyButton();
        loginLbl1 = new javax.swing.JLabel();
        heliosIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setBackground(new java.awt.Color(255, 255, 255));
        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passField.setLabelText("Password");
        loginPane.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 300, 60));

        confirmField.setLabelText("Confirm Password");
        confirmField.setShowAndHide(true);
        confirmField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmFieldActionPerformed(evt);
            }
        });
        loginPane.add(confirmField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 310, 70));

        descLabel.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        descLabel.setForeground(new java.awt.Color(51, 51, 51));
        descLabel.setText("This will be used for your future login.  ");
        loginPane.add(descLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 330, 20));

        descLabel1.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        descLabel1.setForeground(new java.awt.Color(51, 51, 51));
        descLabel1.setText("Create your password for your email..");
        loginPane.add(descLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 410, 20));

        loginLbl.setBackground(new java.awt.Color(25, 25, 25));
        loginLbl.setFont(new java.awt.Font("Arial Black", 3, 36)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(25, 25, 25));
        loginLbl.setText("Create password");
        loginPane.add(loginLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 440, 60));

        signUpButton.setBackground(new java.awt.Color(25, 25, 25));
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Confirm");
        signUpButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        signUpButton.setRadius(50);
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpButtonMouseClicked(evt);
            }
        });
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        loginPane.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 190, 60));

        loginLbl1.setBackground(new java.awt.Color(25, 25, 25));
        loginLbl1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        loginLbl1.setForeground(new java.awt.Color(25, 25, 25));
        loginLbl1.setText("Back");
        loginLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLbl1MouseClicked(evt);
            }
        });
        loginPane.add(loginLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 60));

        jPanel1.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 760, 800));

        heliosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/helios-icon-large.jpg"))); // NOI18N
        jPanel1.add(heliosIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 800));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmFieldActionPerformed

    private void signUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonMouseClicked

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        String password = passField.getText();
        String confirmPassword = confirmField.getText();

        // Validate passwords
        if (password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password fields cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!isValidPassword(password)) {
            // Password validation failed (error message is shown in isValidPassword)
        } else {
            // If passwords are valid, open the completeUserPage frame and pass the email and password
            completeUserPage completePage = new completeUserPage(email, password);
            completePage.setVisible(true);
            this.dispose(); // Close the current frame
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void loginLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLbl1MouseClicked
        // TODO add your handling code here:
        register nw = new register();
        this.dispose();
        nw.setVisible(true);
    }//GEN-LAST:event_loginLbl1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private textfield.PasswordField confirmField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel descLabel1;
    private javax.swing.JLabel heliosIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JLabel loginLbl1;
    private javax.swing.JPanel loginPane;
    private textfield.PasswordField passField;
    private textfield.MyButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
