package adminDash.ManageStaff;

import Error.SomethingWentWrong;
import adminDash.main;
import config.Session;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import loginPage.Main;

public class createStaff extends javax.swing.JFrame {

    public createStaff() {
        initComponents();
    }
    
     // Method to check if the email already exists in the database
    private boolean isEmailDuplicate(String email) {
        dbConnector dbc = new dbConnector();
        String query = "SELECT user_Email FROM tbl_user WHERE user_Email = ?";
        try (Connection conn = dbc.getConnection();
             PreparedStatement pst = conn.prepareStatement(query)) {
            pst.setString(1, email);
            try (ResultSet rs = pst.executeQuery()) {
                return rs.next(); // If a record is found, the email is a duplicate
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return true; // Assume duplicate to prevent further issues
        }
    }
    
    private void logActivity(String description) {
        dbConnector dbc = new dbConnector();
        Connection conn = null;
        PreparedStatement pst = null;

        Session sess = Session.getInstance();

        try {
            String query = "INSERT INTO activity_logs (user_id, description) VALUES (?, ?)";

            conn = dbc.getConnection();
            pst = conn.prepareStatement(query);

            pst.setInt(1, sess.getUid());
            pst.setString(2, description);

            pst.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Error logging activity: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pInfoPanel = new javax.swing.JPanel();
        pInfoHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new textfield.TextField();
        lname = new textfield.TextField();
        txtDate = new textfield.TextField();
        mobileNum = new textfield.TextField();
        mobileNumLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        pInfoPanel1 = new javax.swing.JPanel();
        pInfoHeader1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        emailPane = new textfield.TextField();
        passField = new textfield.PasswordField();
        staffType = new javax.swing.JComboBox<>();
        submitButton = new textfield.MyButton();
        staffStatus = new javax.swing.JComboBox<>();
        userID = new textfield.TextField();
        cancelButton = new textfield.MyButton();
        homePane = new javax.swing.JPanel();
        UserLabel12 = new javax.swing.JLabel();
        UserLabel11 = new javax.swing.JLabel();
        UserLabel10 = new javax.swing.JLabel();
        UserLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1202, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 100));

        pInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        pInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pInfoHeader.setBackground(new java.awt.Color(255, 255, 255));
        pInfoHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setText("Personal-Info");
        pInfoHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 240, 30));

        pInfoPanel.add(pInfoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 50));

        fname.setLabelText("First Name");
        pInfoPanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 330, 60));

        lname.setLabelText("Last Name");
        pInfoPanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 330, 70));

        txtDate.setLabelText("MM--DD--YYYY");
        pInfoPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 330, 50));

        mobileNum.setLabelText("+63");
        pInfoPanel.add(mobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 330, 60));

        mobileNumLabel.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        mobileNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        mobileNumLabel.setText("Mobile Number");
        pInfoPanel.add(mobileNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 110, 20));

        dateLabel.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("Birth Date");
        pInfoPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 20));

        panel1.add(pInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 530, 630));

        pInfoPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pInfoPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pInfoHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pInfoHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setText("Account-Info");
        pInfoHeader1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        pInfoPanel1.add(pInfoHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 530, 50));

        emailPane.setLabelText("Email");
        pInfoPanel1.add(emailPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 390, 60));

        passField.setLabelText("Password");
        pInfoPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 390, 60));

        staffType.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        staffType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type:", "Trainer", "Casher", "Gym Assistant" }));
        pInfoPanel1.add(staffType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 320, 40));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        submitButton.setRadius(50);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        pInfoPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 190, 50));

        staffStatus.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        staffStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Status:", "Active", "Pending" }));
        pInfoPanel1.add(staffStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 320, 40));

        userID.setEnabled(false);
        userID.setLabelText("User ID");
        pInfoPanel1.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 390, 70));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        cancelButton.setRadius(50);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        pInfoPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 190, 50));

        panel1.add(pInfoPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 530, 600));

        homePane.setBackground(new java.awt.Color(255, 255, 255));
        homePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePaneMouseClicked(evt);
            }
        });
        homePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        UserLabel12.setText("Home");
        homePane.add(UserLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        UserLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        UserLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1).png"))); // NOI18N
        homePane.add(UserLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panel1.add(homePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 50));

        UserLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        UserLabel10.setText("Create Staff");
        panel1.add(UserLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 50));

        UserLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        UserLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        panel1.add(UserLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 1, 1350, 940));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 940));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
          // Trim all inputs first
        String firstName = fname.getText().trim();
        String lastName = lname.getText().trim();
        String birthDate = txtDate.getText().trim();
        String phone = mobileNum.getText().trim();
        String email = emailPane.getText().trim();
        String password = new String(passField.getPassword()).trim();
        String staffTypeStr = (staffType.getSelectedItem() != null) ? staffType.getSelectedItem().toString() : "";
        String staffStatusStr = (staffStatus.getSelectedItem() != null) ? staffStatus.getSelectedItem().toString() : "";

        // Validate required fields
        if (firstName.isEmpty() || lastName.isEmpty() || birthDate.isEmpty() || 
            phone.isEmpty() || email.isEmpty() || password.isEmpty() ||
            staffTypeStr.isEmpty() || staffStatusStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "All fields are required.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate email format
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email address.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate date format (adjust pattern as needed)
        if (!birthDate.matches("^\\d{2}-\\d{2}-\\d{4}$")) {
            JOptionPane.showMessageDialog(this,
                "Date must be in MM-DD-YYYY format",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate phone number
        if (!phone.matches("^[0-9]{10,15}$")) {
            JOptionPane.showMessageDialog(this,
                "Phone number must be 10-15 digits",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check for duplicate email
        if (isEmailDuplicate(email)) {
            JOptionPane.showMessageDialog(this, 
                "Email already exists. Please use a different email.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Hash the password using your existing passwordHasher
        String hashedPassword;
        try {
            hashedPassword = passwordHasher.hashPassword(password);
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(this,
                "System error: Password encryption failed",
                "Security Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        dbConnector dbc = new dbConnector();
        String query = "INSERT INTO staff_tbl (staff_Fname, staff_Lname, staff_Birthdate, "
                     + "staff_Email, staff_Pass, staff_Type, staff_Phone, staff_Status) "
                     + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = dbc.getConnection();
             PreparedStatement pst = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {

            // Set parameters
            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, birthDate);
            pst.setString(4, email);
            pst.setString(5, hashedPassword);
            pst.setString(6, staffTypeStr);
            pst.setString(7, phone);
            pst.setString(8, staffStatusStr);

            int rowsInserted = pst.executeUpdate();

            if (rowsInserted > 0) {
                // Get the auto-generated ID
                try (ResultSet generatedKeys = pst.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int newUserId = generatedKeys.getInt(1);
                        // Log the activity
                        String activityDescription = "Added new Staff: " + fname.getText() + 
                                                   " " + lname.getText() + "";
                        logActivity(activityDescription);
                        JOptionPane.showMessageDialog(this,
                            "Staff created successfully! ID: " + newUserId,
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                    }
                }

                // Navigate to user form
                main m = new main();
                m.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                    "Coach creation failed. Please try again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Database error: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        main mc = new main();
        this.dispose();
        mc.setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void homePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePaneMouseClicked
        // TODO add your handling code here:
        main mc = new main();
        this.dispose();
        mc.setVisible(true);
    }//GEN-LAST:event_homePaneMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        if(sess.getUid() == 0){
            SomethingWentWrong sw = new SomethingWentWrong();
            sw.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserLabel10;
    private javax.swing.JLabel UserLabel11;
    private javax.swing.JLabel UserLabel12;
    private javax.swing.JLabel UserLabel7;
    private textfield.MyButton cancelButton;
    private javax.swing.JLabel dateLabel;
    public textfield.TextField emailPane;
    public textfield.TextField fname;
    private javax.swing.JPanel header;
    private javax.swing.JPanel homePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public textfield.TextField lname;
    public textfield.TextField mobileNum;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JPanel pInfoHeader;
    private javax.swing.JPanel pInfoHeader1;
    private javax.swing.JPanel pInfoPanel;
    private javax.swing.JPanel pInfoPanel1;
    private javax.swing.JPanel panel1;
    public textfield.PasswordField passField;
    public javax.swing.JComboBox<String> staffStatus;
    public javax.swing.JComboBox<String> staffType;
    private textfield.MyButton submitButton;
    public textfield.TextField txtDate;
    public textfield.TextField userID;
    // End of variables declaration//GEN-END:variables
}
