package adminDash.ManageStaff;

import Error.SomethingWentWrong;
import adminDash.main;
import config.Session;
import config.dbConnector;
import customTable.TableDarkWithEdit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class updateStaff extends javax.swing.JFrame {

    /**
     * Creates new form updateEquipment
     */
    public updateStaff() {
        initComponents();
    }
    
    public void setParentTable(TableDarkWithEdit table) {
        this.parentTable = table;
    }
    
    
       private boolean isEmailDuplicate(String email, String currentStaffId) {
        dbConnector dbc = new dbConnector();
        try {
            String query = "SELECT COUNT(*) FROM staff_tbl WHERE staff_Email = ? AND staff_id != ?";
            Connection conn = dbc.getConnection();
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, email);
            pst.setString(2, currentStaffId);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pInfoPanel = new javax.swing.JPanel();
        pInfoHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new textfield.TextField();
        lname = new textfield.TextField();
        txtDate = new textfield.TextField();
        mobileNum = new textfield.TextField();
        mobileNumLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        pInfoPanel1 = new javax.swing.JPanel();
        pInfoHeader1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        emailPane = new textfield.TextField();
        staffType = new javax.swing.JComboBox<>();
        submitButton = new textfield.MyButton();
        staffStatus = new javax.swing.JComboBox<>();
        staffID = new textfield.TextField();
        cancelButton = new textfield.MyButton();
        UserLabel7 = new javax.swing.JLabel();
        UserLabel10 = new javax.swing.JLabel();
        homePane = new javax.swing.JPanel();
        UserLabel12 = new javax.swing.JLabel();
        UserLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(27, 27, 27));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/heliosIcon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1206, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1340, 110));

        pInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        pInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pInfoHeader.setBackground(new java.awt.Color(255, 255, 255));
        pInfoHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setText("Personal-Info");
        pInfoHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 240, 30));

        pInfoPanel.add(pInfoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 50));

        fname.setLabelText("First Name");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        pInfoPanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 310, 60));

        lname.setLabelText("Last Name");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        pInfoPanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 310, 60));

        txtDate.setLabelText("MM--DD--YYYY");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        pInfoPanel.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 300, 60));

        mobileNum.setLabelText("+63");
        mobileNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNumActionPerformed(evt);
            }
        });
        pInfoPanel.add(mobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 300, 50));

        mobileNumLabel.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        mobileNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        mobileNumLabel.setText("Mobile Number");
        pInfoPanel.add(mobileNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, 20));

        dateLabel.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(51, 51, 51));
        dateLabel.setText("Birth Date");
        pInfoPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, 20));

        panel1.add(pInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 450, 480));

        pInfoPanel1.setBackground(new java.awt.Color(255, 255, 255));
        pInfoPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pInfoHeader1.setBackground(new java.awt.Color(255, 255, 255));
        pInfoHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel2.setText("Account-Info");
        pInfoHeader1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        pInfoPanel1.add(pInfoHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 50));

        emailPane.setLabelText("Email");
        emailPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailPaneActionPerformed(evt);
            }
        });
        pInfoPanel1.add(emailPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 310, 50));

        staffType.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        staffType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type:", "Trainer", "Casher", "Gym Assistant" }));
        staffType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffTypeActionPerformed(evt);
            }
        });
        pInfoPanel1.add(staffType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 320, 60));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        submitButton.setRadius(50);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        pInfoPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 190, 60));

        staffStatus.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        staffStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account Status:", "Active", "Pending" }));
        staffStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffStatusActionPerformed(evt);
            }
        });
        pInfoPanel1.add(staffStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 320, 60));

        staffID.setEnabled(false);
        staffID.setLabelText("User ID");
        staffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffIDActionPerformed(evt);
            }
        });
        pInfoPanel1.add(staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 70, 310, 60));

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        cancelButton.setRadius(50);
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        pInfoPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 210, 60));

        panel1.add(pInfoPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 530, 560));

        UserLabel7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        UserLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right-arrow.png"))); // NOI18N
        panel1.add(UserLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        UserLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        UserLabel10.setText("Update Staff");
        panel1.add(UserLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 160, 50));

        homePane.setBackground(new java.awt.Color(255, 255, 255));
        homePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePaneMouseClicked(evt);
            }
        });
        homePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        UserLabel12.setText("Home");
        homePane.add(UserLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 30));

        UserLabel11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        UserLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home (1).png"))); // NOI18N
        homePane.add(UserLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panel1.add(homePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 50));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1340, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered

    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited

    }//GEN-LAST:event_jLabel3MouseExited

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void mobileNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNumActionPerformed

    private void emailPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailPaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailPaneActionPerformed

    private void staffTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffTypeActionPerformed

    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Trim all inputs first
        String firstName = fname.getText().trim();
        String lastName = lname.getText().trim();
        String birthDate = txtDate.getText().trim();
        String phone = mobileNum.getText().trim();
        String email = emailPane.getText().trim();
        String staffTypeStr = (staffType.getSelectedItem() != null) ? staffType.getSelectedItem().toString() : "";
        String staffStatusStr = (staffStatus.getSelectedItem() != null) ? staffStatus.getSelectedItem().toString() : "";

        // Validate required fields
        if (firstName.isEmpty() || lastName.isEmpty() || birthDate.isEmpty() || 
            phone.isEmpty() || staffTypeStr.isEmpty() || email.isEmpty() || staffStatusStr.isEmpty()) {
            showError("All fields are required and must be properly selected.");
            return;
        }

        // Validate email format
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
            showError("Please enter a valid email address.");
            return;
        }

        // Validate date format (MM-DD-YYYY)
        if (!birthDate.matches("^\\d{2}-\\d{2}-\\d{4}$")) {
            showError("Date must be in MM-DD-YYYY format.");
            return;
        }

        // Validate phone number (digits only, 10-15 chars)
        if (!phone.matches("^[0-9]{10,15}$")) {
            showError("Phone number must be 10-15 digits.");
            return;
        }

        // Check for duplicate email (excluding current staff)
        if (isEmailDuplicate(email, staffID.getText())) {
            showError("Email already exists. Please use a different email.");
            return;
        }

        // Database update
        dbConnector dbc = new dbConnector();
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            String query = "UPDATE staff_tbl SET "
                + "staff_Fname = ?, "
                + "staff_Lname = ?, "
                + "staff_Birthdate = ?, "
                + "staff_Email = ?, "
                + "staff_Type = ?, "
                + "staff_Phone = ?, "
                + "staff_Status = ? "
                + "WHERE staff_id = ?";

            conn = dbc.getConnection();
            pst = conn.prepareStatement(query);

            pst.setString(1, firstName);
            pst.setString(2, lastName);
            pst.setString(3, birthDate);
            pst.setString(4, email);
            pst.setString(5, staffTypeStr);
            pst.setString(6, phone);
            pst.setString(7, staffStatusStr);
            pst.setString(8, staffID.getText().trim());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this,
                    "Staff updated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

                // Refresh parent table if it exists
                if (parentTable != null) {
                    parentTable.refreshTable();
                }

                this.dispose(); // Close the form
            } else {
                JOptionPane.showMessageDialog(this,
                    "No staff found with the specified ID.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            showError("Database error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            try {   
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed
  
    // Add this field at the class level
    private TableDarkWithEdit parentTable;
    
    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    private void staffStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffStatusActionPerformed

    private void staffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffIDActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        main mc = new main();
        this.dispose();
        mc.setVisible(true);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void homePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePaneMouseClicked
        // TODO add your handling code here:
        main mc = new main();
        this.dispose();
        mc.setVisible(true);
    }//GEN-LAST:event_homePaneMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Session sess = Session.getInstance();
        if(sess.getUid() == 0){
            SomethingWentWrong sw = new SomethingWentWrong();
            sw.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserLabel10;
    private javax.swing.JLabel UserLabel11;
    private javax.swing.JLabel UserLabel12;
    private javax.swing.JLabel UserLabel7;
    private textfield.MyButton cancelButton;
    private javax.swing.JLabel dateLabel;
    public textfield.TextField emailPane;
    public textfield.TextField fname;
    private javax.swing.JPanel header;
    private javax.swing.JPanel homePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public textfield.TextField lname;
    public textfield.TextField mobileNum;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JPanel pInfoHeader;
    private javax.swing.JPanel pInfoHeader1;
    private javax.swing.JPanel pInfoPanel;
    private javax.swing.JPanel pInfoPanel1;
    private javax.swing.JPanel panel1;
    public textfield.TextField staffID;
    public javax.swing.JComboBox<String> staffStatus;
    public javax.swing.JComboBox<String> staffType;
    private textfield.MyButton submitButton;
    public textfield.TextField txtDate;
    // End of variables declaration//GEN-END:variables
}
